apiVersion: v1
kind: Service
metadata:
  name: cafe
spec:
  type: NodePort
  ports:
  - port: 80 # cổng dịch vụ ánh xạ vào cổng POD
    targetPort: 80 # cổng POD ánh xạ vào container
    protocol: TCP
    name: http
    nodePort: 31880 # cổng NODE ánh xạ vào cổng dịch vụ
  selector:
    app: cafe
